= Lab 04

== Modularize Tasks and Link Multiple Jobs

. It is very common within an application's git repository to place all concourse artifacts in a _ci_ folder.  Within that folder individual tasks are modularized in their own yml files and refer to shell scripts for actual task execution.  E.G.
+
[source, bash]
---------------------------------------------------------------------
App Git Repo Root:
├── App source code....
│   ├── Some code artifacts...
├── ci
│   ├── pipeline.yml
│   ├── credentials.yml
│   ├── tasks
│   │   ├── modular-task.yml
│   │   ├── modular-task.sh
---------------------------------------------------------------------
+
We will mimic that structure as we build out our pipeline

. Create the _ci_ and _ci/tasks_ directory structure:
+
[source,bash]
---------------------------------------------------------------------
$ mkdir -p ci/tasks
---------------------------------------------------------------------

. Move the pipeline.yml file into your new _ci_ directory
+
[source,bash]
---------------------------------------------------------------------
$ mv pipeline.yml ci/pipeline.yml
---------------------------------------------------------------------

. We will now create modularized tasks for the steps to build our application.  First create the yml task file _mvn-test.yml_.  Create the file in the _ci/tasks_ directory:
+
[source, bash]
---------------------------------------------------------------------
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jamesdbloom/docker-java8-maven
    tag: "latest"

inputs:
- name: git-assets

run:
  path: git-assets/boot-sample/ci/tasks/test.sh
---------------------------------------------------------------------

. You'll note that this task references to script _test.sh_ for the actual execution logic.  Create that file:
+
[source, bash]
---------------------------------------------------------------------
#!/bin/bash

set -xe

cd git-assets/boot-sample
mvn test
---------------------------------------------------------------------

. Create similar artifacts for the packaging stage of your application build:
+
_ci/tasks/mvn-package.yml_
+
[source,bash]
---------------------------------------------------------------------
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jamesdbloom/docker-java8-maven
    tag: "latest"

inputs:
- name: git-assets

outputs:
- name: app-output

run:
  path: git-assets/boot-sample/ci/tasks/package.sh
---------------------------------------------------------------------
+
_ci/tasks/package.sh_
+
[source,bash]
---------------------------------------------------------------------
#!/bin/bash

set -xe

cd git-assets/boot-sample
mvn package
cp target/concourse-demo-*.jar ../../app-output/concourse-demo.jar
---------------------------------------------------------------------

. We need to make sure our bash scripts are executable.  Execute the following command:
+
[source,bash]
---------------------------------------------------------------------
$ chmod +x ci/tasks/*.sh
---------------------------------------------------------------------

.  Modify your main _pipleine.yml_, which now resides in the the ci directory, to include the 2 new tasks.  These tasks will represent completely new jobs in your pipeline.  These will test and package the java code included in your repository.  You will be replacing your "howdy" job.  Your final pipeline.yml file should look like this:
+
[source,bash]
---------------------------------------------------------------------
resources:
- name: git-assets
  type: git
  source:
    branch: master
    uri: https://github.com/azwickey-pivotal/concourse-workshop

jobs:
- name: unit-test
  public: true
  plan:
  - get: git-assets
    trigger: true
  - task: mvn-test
    file: git-assets/boot-sample/ci/tasks/mvn-test.yml
- name: deploy
  public: true
  plan:
  - get: git-assets
    trigger: true
    passed:
      - unit-test
  - task: mvn-package
    file: git-assets/boot-sample/ci/tasks/mvn-package.yml
---------------------------------------------------------------------

. Update your concourse pipeline with the set-pipeline command.  Remember, your pipeline.yml file is now in a different location:
+
[source,bash]
---------------------------------------------------------------------
$ fly -t gcp set-pipeline -p pipeline-<LASTNAME> -c ci/pipeline.yml
---------------------------------------------------------------------
